version: '3'

volumes:
  postgresdata:

services:
  api:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      PORT: 8080
      DB_URL: postgres://root:password@localhost:5432/slax

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresdata:/var/lib/postgressql/data