version: '3'

volumes:
  postgresdata:

services:
  api:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_PORT=5432

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresdata:/var/lib/postgressql/data