version: '3'

volumes:
  mongodata:

services:
  api:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      - MONGODB_CONNSTRING=mongodb://mongodb:27017/slaxnetwork

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    environment:
      - MONGO_DATA_DIR:/data/db
    volumes:
      - mongodata:/data/db